# Generated by Django 2.2.7 on 2019-12-05 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('articleNo', models.IntegerField(primary_key=True, serialize=False)),
                ('BasePrice', models.IntegerField()),
                ('MRP', models.IntegerField()),
                ('GST', models.IntegerField()),
                ('AgreedMargin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=15)),
                ('GSTNo', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('InvoiceNo', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Supplier')),
                ('items', models.ManyToManyField(to='api.Items')),
            ],
        ),
    ]
