# Generated by Django 2.2.7 on 2019-12-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191205_0635'),
    ]

    operations = [
    ]
