# Generated by Django 2.2.7 on 2019-12-05 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191205_0643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoices',
            new_name='Invoice',
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
