# Generated by Django 2.2.7 on 2019-12-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191205_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='BasePrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='GST',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='MRP',
            field=models.FloatField(),
        ),
    ]
